start: statement*

?statement: assignment
         | if_statement
         | function_declaration
         | for_statement
         | break_statement
         | continue_statement
         | return_statement
         | function_call

?expression: STRING
     | NUMBER
     | IDENTIFIER -> variable
     | access_member
     | function_call

assignment: IDENTIFIER [":" IDENTIFIER] "=" expression

if_statement: "if" expression block

function_declaration: "function" IDENTIFIER "(" [parameters] ")" block
parameters: parameter ("," parameter)*
parameter: IDENTIFIER [":" IDENTIFIER]

for_statement: "for" IDENTIFIER "in" expression block
break_statement: "break"
continue_statement: "continue"

return_statement: "return" expression?

function_call: expression "(" arguments? ")"
arguments: expression ("," expression)*

access_member: expression "." IDENTIFIER

block: "{" statement* "}"

IDENTIFIER: /[a-zA-Z_][a-zA-Z0-9_]*/

%import common.ESCAPED_STRING
STRING: ESCAPED_STRING

NUMBER: /\d+/

// --- comments ---
%import common.CPP_COMMENT
%import common.C_COMMENT

%ignore CPP_COMMENT
%ignore C_COMMENT

// --- whitespace ---
%import common.WS
%ignore WS